import type { IDailyQuizPack, IDailyQuizQuestion } from "./daily-quiz-types";

const QUESTIONS: readonly IDailyQuizQuestion[] = [
  // ---------------------------------------------------------------- science
  {
    id: "science-001",
    category: "science",
    prompt: "What is the chemical symbol for gold?",
    choices: ["Ag", "Au", "Gd", "Go"],
    correctIndex: 1,
    explanation: "Au comes from the Latin word aurum.",
  },
  {
    id: "science-002",
    category: "science",
    prompt: "Which gas do plants take in from the air for photosynthesis?",
    choices: ["Oxygen", "Nitrogen", "Hydrogen", "Carbon dioxide"],
    correctIndex: 3,
    explanation: "Plants combine carbon dioxide and water using light to make sugar.",
  },
  {
    id: "science-003",
    category: "science",
    prompt: "Which planet is closest to the Sun?",
    choices: ["Mercury", "Venus", "Earth", "Mars"],
    correctIndex: 0,
    explanation: "Mercury orbits the Sun at roughly a third of Earth's distance.",
  },
  {
    id: "science-004",
    category: "science",
    prompt: "At sea level, at what temperature does water boil?",
    choices: ["50 °C", "90 °C", "100 °C", "212 °C"],
    correctIndex: 2,
    explanation: "100 °C is the same temperature as 212 °F.",
  },
  {
    id: "science-005",
    category: "science",
    prompt: "Which particle in an atom carries a negative electric charge?",
    choices: ["Proton", "Neutron", "Electron", "Photon"],
    correctIndex: 2,
    explanation: "Electrons are negative, protons positive, and neutrons neutral.",
  },
  {
    id: "science-006",
    category: "science",
    prompt: "What everyday substance has the chemical formula H2O?",
    choices: ["Water", "Hydrogen peroxide", "Table salt", "Ammonia"],
    correctIndex: 0,
    explanation: "Each water molecule has two hydrogen atoms and one oxygen atom.",
  },
  {
    id: "science-007",
    category: "science",
    prompt: "Which force keeps the planets in orbit around the Sun?",
    choices: ["Magnetism", "Friction", "Static electricity", "Gravity"],
    correctIndex: 3,
    explanation: "The Sun's gravity continually pulls the planets toward it.",
  },
  {
    id: "science-008",
    category: "science",
    prompt: "Roughly how fast does light travel through a vacuum?",
    choices: ["30,000 km/s", "300,000 km/s", "3,000,000 km/s", "3,000 km/s"],
    correctIndex: 1,
    explanation: "Light covers about 300,000 kilometres every second.",
  },
  {
    id: "science-009",
    category: "science",
    prompt: "Which gas makes up the largest share of Earth's atmosphere?",
    choices: ["Nitrogen", "Oxygen", "Argon", "Carbon dioxide"],
    correctIndex: 0,
    explanation: "Nitrogen is about 78% of the air; oxygen is about 21%.",
  },
  {
    id: "science-010",
    category: "science",
    prompt: "What is the chemical symbol for sodium?",
    choices: ["So", "Sd", "Na", "S"],
    correctIndex: 2,
    explanation: "Na comes from natrium, the Latin name for the element.",
  },
  {
    id: "science-011",
    category: "science",
    prompt: "Which planet is famous for its bright, wide ring system?",
    choices: ["Jupiter", "Saturn", "Neptune", "Mars"],
    correctIndex: 1,
    explanation: "Saturn's rings are mostly ice and are visible in a small telescope.",
  },
  {
    id: "science-012",
    category: "science",
    prompt: "How many bones does a typical adult human skeleton have?",
    choices: ["106", "186", "226", "206"],
    correctIndex: 3,
    explanation: "Babies have more bones, but many fuse together as they grow.",
  },
  {
    id: "science-013",
    category: "science",
    prompt: "What is the unit of electrical resistance?",
    choices: ["Volt", "Ampere", "Watt", "Ohm"],
    correctIndex: 3,
    explanation: "The ohm is named after the physicist Georg Ohm.",
  },
  {
    id: "science-014",
    category: "science",
    prompt: "Which element has the atomic number 1?",
    choices: ["Helium", "Hydrogen", "Lithium", "Carbon"],
    correctIndex: 1,
    explanation: "Hydrogen has a single proton, so it sits first on the periodic table.",
  },
  {
    id: "science-015",
    category: "science",
    prompt: "Which of these is the hardest naturally occurring mineral?",
    choices: ["Quartz", "Topaz", "Diamond", "Corundum"],
    correctIndex: 2,
    explanation: "Diamond scores 10, the top of the Mohs hardness scale.",
  },
  {
    id: "science-016",
    category: "science",
    prompt: "What is the dense central part of an atom called?",
    choices: ["Nucleus", "Orbital", "Shell", "Lattice"],
    correctIndex: 0,
    explanation: "The nucleus holds the protons and neutrons.",
  },
  {
    id: "science-017",
    category: "science",
    prompt: "Which blood cells carry oxygen around the body?",
    choices: ["White blood cells", "Platelets", "Red blood cells", "Plasma cells"],
    correctIndex: 2,
    explanation: "Red blood cells carry oxygen using the protein haemoglobin.",
  },
  {
    id: "science-018",
    category: "science",
    prompt: "What does the abbreviation DNA stand for?",
    choices: [
      "Deoxyribonucleic acid",
      "Dinucleic acid",
      "Deoxyribose nitrate",
      "Dual nucleic acid",
    ],
    correctIndex: 0,
    explanation: "DNA carries the genetic instructions of living things.",
  },
  {
    id: "science-019",
    category: "science",
    prompt: "At what temperature does water freeze on the Fahrenheit scale?",
    choices: ["0 °F", "32 °F", "100 °F", "212 °F"],
    correctIndex: 1,
    explanation: "32 °F is the same temperature as 0 °C.",
  },
  {
    id: "science-020",
    category: "science",
    prompt: "Which state of matter has a fixed volume but takes the shape of its container?",
    choices: ["Solid", "Gas", "Plasma", "Liquid"],
    correctIndex: 3,
    explanation: "Liquids flow to fit their container but do not expand to fill it.",
  },

  // -------------------------------------------------------------- geography
  {
    id: "geography-001",
    category: "geography",
    prompt: "What is the capital city of Australia?",
    choices: ["Sydney", "Melbourne", "Canberra", "Perth"],
    correctIndex: 2,
    explanation: "Canberra was purpose-built as a compromise between Sydney and Melbourne.",
  },
  {
    id: "geography-002",
    category: "geography",
    prompt: "Which is the largest ocean on Earth?",
    choices: ["Pacific", "Atlantic", "Indian", "Arctic"],
    correctIndex: 0,
    explanation: "The Pacific covers more area than all the land on Earth combined.",
  },
  {
    id: "geography-003",
    category: "geography",
    prompt: "Which river carries the most water of any river in South America?",
    choices: ["Paraná", "Orinoco", "São Francisco", "Amazon"],
    correctIndex: 3,
    explanation: "The Amazon discharges more water than any other river in the world.",
  },
  {
    id: "geography-004",
    category: "geography",
    prompt: "On which continent is the Sahara Desert?",
    choices: ["Asia", "Africa", "Australia", "South America"],
    correctIndex: 1,
    explanation: "The Sahara stretches across much of northern Africa.",
  },
  {
    id: "geography-005",
    category: "geography",
    prompt: "What is the capital city of Canada?",
    choices: ["Ottawa", "Toronto", "Vancouver", "Montreal"],
    correctIndex: 0,
    explanation: "Ottawa sits in the province of Ontario, on the border with Quebec.",
  },
  {
    id: "geography-006",
    category: "geography",
    prompt: "Mount Everest lies on the border between Nepal and which other country?",
    choices: ["India", "Bhutan", "Pakistan", "China"],
    correctIndex: 3,
    explanation: "The summit is on the border of Nepal and the Tibet region of China.",
  },
  {
    id: "geography-007",
    category: "geography",
    prompt: "Which imaginary line divides Earth into the Northern and Southern Hemispheres?",
    choices: ["Prime Meridian", "Equator", "Tropic of Cancer", "Arctic Circle"],
    correctIndex: 1,
    explanation: "The Equator sits at 0° latitude, halfway between the poles.",
  },
  {
    id: "geography-008",
    category: "geography",
    prompt: "What is the capital city of Japan?",
    choices: ["Kyoto", "Osaka", "Tokyo", "Nagoya"],
    correctIndex: 2,
    explanation: "Kyoto was the former imperial capital before Tokyo.",
  },
  {
    id: "geography-009",
    category: "geography",
    prompt: "Which continent is the smallest by land area?",
    choices: ["Europe", "Antarctica", "South America", "Australia"],
    correctIndex: 3,
  },
  {
    id: "geography-010",
    category: "geography",
    prompt: "Which river flows through the city of Cairo?",
    choices: ["Nile", "Congo", "Niger", "Zambezi"],
    correctIndex: 0,
    explanation: "The Nile runs north through Egypt to the Mediterranean Sea.",
  },
  {
    id: "geography-011",
    category: "geography",
    prompt: "In which country is the city of Marrakesh?",
    choices: ["Egypt", "Algeria", "Morocco", "Tunisia"],
    correctIndex: 2,
    explanation: "Marrakesh is one of Morocco's historic imperial cities.",
  },
  {
    id: "geography-012",
    category: "geography",
    prompt: "What is the capital city of Brazil?",
    choices: ["Rio de Janeiro", "Brasília", "São Paulo", "Salvador"],
    correctIndex: 1,
    explanation: "Brasília replaced Rio de Janeiro as the capital in 1960.",
  },
  {
    id: "geography-013",
    category: "geography",
    prompt: "Which mountain range is traditionally used as the boundary between Europe and Asia?",
    choices: ["Alps", "Urals", "Carpathians", "Pyrenees"],
    correctIndex: 1,
    explanation: "The Urals run north to south through western Russia.",
  },
  {
    id: "geography-014",
    category: "geography",
    prompt: "Which strait separates Spain from Morocco?",
    choices: ["Bosporus", "Strait of Hormuz", "Strait of Malacca", "Strait of Gibraltar"],
    correctIndex: 3,
    explanation: "The Strait of Gibraltar links the Atlantic Ocean to the Mediterranean.",
  },
  {
    id: "geography-015",
    category: "geography",
    prompt: "What is the capital city of Kenya?",
    choices: ["Nairobi", "Mombasa", "Kampala", "Dar es Salaam"],
    correctIndex: 0,
    explanation: "Mombasa is Kenya's main port, but Nairobi is the capital.",
  },
  {
    id: "geography-016",
    category: "geography",
    prompt: "Not counting Australia, which is the largest island in the world?",
    choices: ["Borneo", "Madagascar", "Greenland", "New Guinea"],
    correctIndex: 2,
    explanation: "Greenland is about three times the size of New Guinea.",
  },
  {
    id: "geography-017",
    category: "geography",
    prompt: "Lisbon is the capital of which country?",
    choices: ["Portugal", "Spain", "Italy", "Greece"],
    correctIndex: 0,
    explanation: "Lisbon sits on the Atlantic coast at the mouth of the Tagus river.",
  },
  {
    id: "geography-018",
    category: "geography",
    prompt: "Which ocean lies between the east coast of Africa and the west coast of Australia?",
    choices: ["Atlantic", "Pacific", "Indian", "Arctic"],
    correctIndex: 2,
    explanation: "The Indian Ocean is the third largest ocean.",
  },
  {
    id: "geography-019",
    category: "geography",
    prompt: "What is the capital city of Argentina?",
    choices: ["Santiago", "Montevideo", "Lima", "Buenos Aires"],
    correctIndex: 3,
    explanation: "Buenos Aires faces Montevideo across the Río de la Plata.",
  },
  {
    id: "geography-020",
    category: "geography",
    prompt: "In which country is the city of Istanbul?",
    choices: ["Greece", "Turkey", "Bulgaria", "Syria"],
    correctIndex: 1,
    explanation: "Istanbul straddles the Bosporus, with parts in both Europe and Asia.",
  },

  // ---------------------------------------------------------------- history
  {
    id: "history-001",
    category: "history",
    prompt: "In which year did the Berlin Wall come down?",
    choices: ["1979", "1985", "1991", "1989"],
    correctIndex: 3,
    explanation: "The wall opened in November 1989; Germany reunified in 1990.",
  },
  {
    id: "history-002",
    category: "history",
    prompt: "Who was the first President of the United States?",
    choices: ["Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin"],
    correctIndex: 1,
    explanation: "Washington took office in 1789 and served two terms.",
  },
  {
    id: "history-003",
    category: "history",
    prompt: "Which ancient civilization built the pyramids at Giza?",
    choices: ["Romans", "Greeks", "Egyptians", "Babylonians"],
    correctIndex: 2,
    explanation: "The Great Pyramid was built around 2500 BC as a royal tomb.",
  },
  {
    id: "history-004",
    category: "history",
    prompt: "In which year did the Second World War end?",
    choices: ["1945", "1944", "1946", "1939"],
    correctIndex: 0,
    explanation: "Germany surrendered in May 1945 and Japan in September 1945.",
  },
  {
    id: "history-005",
    category: "history",
    prompt: "Augustus was the first emperor of which empire?",
    choices: ["Ottoman", "Roman", "Persian", "Mongol"],
    correctIndex: 1,
    explanation: "Augustus became the first Roman emperor in 27 BC.",
  },
  {
    id: "history-006",
    category: "history",
    prompt: "Who was the first person to walk on the Moon?",
    choices: ["Buzz Aldrin", "Yuri Gagarin", "John Glenn", "Neil Armstrong"],
    correctIndex: 3,
    explanation: "Armstrong stepped onto the Moon in July 1969 during Apollo 11.",
  },
  {
    id: "history-007",
    category: "history",
    prompt: "In which year did the Titanic sink on its maiden voyage?",
    choices: ["1912", "1905", "1921", "1898"],
    correctIndex: 0,
    explanation: "The ship struck an iceberg in the North Atlantic in April 1912.",
  },
  {
    id: "history-008",
    category: "history",
    prompt: "Which document, sealed in 1215, limited the powers of the English king?",
    choices: ["Bill of Rights", "Domesday Book", "Magna Carta", "Act of Union"],
    correctIndex: 2,
    explanation: "King John agreed to Magna Carta under pressure from his barons.",
  },
  {
    id: "history-009",
    category: "history",
    prompt: "Who introduced the movable-type printing press to Europe in the 1400s?",
    choices: ["Johannes Gutenberg", "Martin Luther", "Leonardo da Vinci", "Isaac Newton"],
    correctIndex: 0,
    explanation: "Gutenberg's press made books far cheaper to produce.",
  },
  {
    id: "history-010",
    category: "history",
    prompt: "The Vikings originally came from which region?",
    choices: ["Germany", "Scandinavia", "Britain", "Russia"],
    correctIndex: 1,
    explanation: "Viking raiders and traders set out from Norway, Sweden, and Denmark.",
  },
  {
    id: "history-011",
    category: "history",
    prompt: "In which year did Christopher Columbus first reach the Americas?",
    choices: ["1512", "1452", "1502", "1492"],
    correctIndex: 3,
    explanation: "His first voyage landed in the Caribbean in October 1492.",
  },
  {
    id: "history-012",
    category: "history",
    prompt: "In which year did the French Revolution begin?",
    choices: ["1776", "1799", "1789", "1815"],
    correctIndex: 2,
    explanation: "The storming of the Bastille took place in July 1789.",
  },
  {
    id: "history-013",
    category: "history",
    prompt: "Which Greek philosopher was the tutor of Alexander the Great?",
    choices: ["Socrates", "Plato", "Aristotle", "Pythagoras"],
    correctIndex: 2,
    explanation: "Aristotle taught the young Alexander in Macedonia.",
  },
  {
    id: "history-014",
    category: "history",
    prompt: "What was the name of the ship that carried the Pilgrims to America in 1620?",
    choices: ["Mayflower", "Santa Maria", "Endeavour", "Beagle"],
    correctIndex: 0,
    explanation: "The Mayflower landed at what became Plymouth Colony.",
  },
  {
    id: "history-015",
    category: "history",
    prompt: "Which war was fought between the northern and southern states of the USA?",
    choices: ["Revolutionary War", "Civil War", "War of 1812", "Mexican-American War"],
    correctIndex: 1,
    explanation: "The American Civil War lasted from 1861 to 1865.",
  },
  {
    id: "history-016",
    category: "history",
    prompt: "Which structure was built over centuries to guard China's northern frontier?",
    choices: ["Hadrian's Wall", "Berlin Wall", "Walls of Constantinople", "Great Wall of China"],
    correctIndex: 3,
    explanation: "Sections of the Great Wall date back more than two thousand years.",
  },
  {
    id: "history-017",
    category: "history",
    prompt: "Who was Prime Minister of the United Kingdom for most of the Second World War?",
    choices: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "David Lloyd George"],
    correctIndex: 1,
    explanation: "Churchill took office in May 1940 and led Britain until 1945.",
  },
  {
    id: "history-018",
    category: "history",
    prompt: "In which year did a human first travel into space?",
    choices: ["1961", "1957", "1969", "1965"],
    correctIndex: 0,
    explanation: "Yuri Gagarin orbited Earth in April 1961.",
  },
  {
    id: "history-019",
    category: "history",
    prompt: "Which Roman city was buried by the eruption of Mount Vesuvius in AD 79?",
    choices: ["Athens", "Carthage", "Troy", "Pompeii"],
    correctIndex: 3,
    explanation: "Ash preserved Pompeii until it was rediscovered centuries later.",
  },
  {
    id: "history-020",
    category: "history",
    prompt: "In which country did the Renaissance begin?",
    choices: ["France", "Spain", "Italy", "England"],
    correctIndex: 2,
    explanation: "The Renaissance took root in Italian cities such as Florence.",
  },

  // --------------------------------------------------------------- language
  {
    id: "language-001",
    category: "language",
    prompt: 'What is the plural of the word "mouse" when referring to the animal?',
    choices: ["Mice", "Mouses", "Mousen", "Mices"],
    correctIndex: 0,
    explanation: "Mouse is one of a small set of English nouns with an irregular plural.",
  },
  {
    id: "language-002",
    category: "language",
    prompt: "What is a group of lions called?",
    choices: ["Herd", "Pack", "Pride", "Flock"],
    correctIndex: 2,
    explanation: "A pride is usually made up of related females and their cubs.",
  },
  {
    id: "language-003",
    category: "language",
    prompt: 'Which of these words is a synonym for "happy"?',
    choices: ["Gloomy", "Joyful", "Weary", "Furious"],
    correctIndex: 1,
    explanation: "A synonym is a word with nearly the same meaning as another.",
  },
  {
    id: "language-004",
    category: "language",
    prompt: 'What is the simple past tense of the verb "go"?',
    choices: ["Goed", "Gone", "Going", "Went"],
    correctIndex: 3,
    explanation: '"Gone" is the past participle, as in "has gone".',
  },
  {
    id: "language-005",
    category: "language",
    prompt: "Which of these words is a palindrome?",
    choices: ["Apple", "River", "Stone", "Level"],
    correctIndex: 3,
    explanation: "A palindrome reads the same forwards and backwards.",
  },
  {
    id: "language-006",
    category: "language",
    prompt: 'The word "alphabet" is built from the first two letters of which alphabet?',
    choices: ["Latin", "Greek", "Hebrew", "Arabic"],
    correctIndex: 1,
    explanation: "Alpha and beta are the first two Greek letters.",
  },
  {
    id: "language-007",
    category: "language",
    prompt: 'What part of speech is the word "quickly"?',
    choices: ["Adverb", "Noun", "Adjective", "Verb"],
    correctIndex: 0,
    explanation: "Adverbs describe how, when, or where an action happens.",
  },
  {
    id: "language-008",
    category: "language",
    prompt: "What do we call two words that sound alike but have different meanings?",
    choices: ["Synonyms", "Antonyms", "Homophones", "Acronyms"],
    correctIndex: 2,
    explanation: '"Flour" and "flower" are a classic pair of homophones.',
  },
  {
    id: "language-009",
    category: "language",
    prompt: 'From which language did English borrow the words "piano" and "opera"?',
    choices: ["French", "Italian", "Spanish", "German"],
    correctIndex: 1,
    explanation: "Many musical terms entered English from Italian.",
  },
  {
    id: "language-010",
    category: "language",
    prompt: 'What is the plural of "child"?',
    choices: ["Children", "Childs", "Childes", "Childer"],
    correctIndex: 0,
  },
  {
    id: "language-011",
    category: "language",
    prompt: "Which punctuation mark normally ends a direct question?",
    choices: ["Full stop", "Comma", "Colon", "Question mark"],
    correctIndex: 3,
  },
  {
    id: "language-012",
    category: "language",
    prompt: "What is the traditional collective noun for a group of crows?",
    choices: ["Swarm", "Gaggle", "Murder", "School"],
    correctIndex: 2,
    explanation: "A gaggle is geese, a school is fish, and a murder is crows.",
  },
  {
    id: "language-013",
    category: "language",
    prompt: 'Which word is the opposite of "ancient"?',
    choices: ["Modern", "Old", "Antique", "Historic"],
    correctIndex: 0,
    explanation: "The other three all describe things from the past.",
  },
  {
    id: "language-014",
    category: "language",
    prompt: 'From which language does the word "kindergarten" come?',
    choices: ["Dutch", "Swedish", "French", "German"],
    correctIndex: 3,
    explanation: 'It literally means "children\'s garden" in German.',
  },
  {
    id: "language-015",
    category: "language",
    prompt: "Which of these is the correct spelling?",
    choices: ["Recieve", "Receve", "Receive", "Riceive"],
    correctIndex: 2,
    explanation: 'The usual rule is "i before e except after c".',
  },
  {
    id: "language-016",
    category: "language",
    prompt: "What do we call a word formed from the first letters of other words, such as NASA?",
    choices: ["Anagram", "Acronym", "Antonym", "Idiom"],
    correctIndex: 1,
    explanation: "An acronym is pronounced as a word, unlike an initialism such as FBI.",
  },
  {
    id: "language-017",
    category: "language",
    prompt: "How many letters are there in the modern English alphabet?",
    choices: ["24", "25", "26", "27"],
    correctIndex: 2,
  },
  {
    id: "language-018",
    category: "language",
    prompt: "Spanish, French, and Italian all developed from which ancient language?",
    choices: ["Greek", "Latin", "Sanskrit", "Celtic"],
    correctIndex: 1,
    explanation: "They are Romance languages, descended from the Latin of the Roman Empire.",
  },
  {
    id: "language-019",
    category: "language",
    prompt: 'What is the comparative form of the adjective "good"?',
    choices: ["Gooder", "More good", "Best", "Better"],
    correctIndex: 3,
    explanation: '"Good, better, best" is an irregular comparison.',
  },
  {
    id: "language-020",
    category: "language",
    prompt: "What do we call a word that means the opposite of another word?",
    choices: ["Antonym", "Synonym", "Homonym", "Pseudonym"],
    correctIndex: 0,
    explanation: '"Hot" and "cold" are antonyms.',
  },

  // ------------------------------------------------------------- technology
  {
    id: "technology-001",
    category: "technology",
    prompt: "How many bits are there in one byte?",
    choices: ["4", "8", "16", "32"],
    correctIndex: 1,
    explanation: "A byte of 8 bits can represent 256 different values.",
  },
  {
    id: "technology-002",
    category: "technology",
    prompt: "What does HTTP stand for?",
    choices: [
      "HyperText Transfer Protocol",
      "High Transfer Text Process",
      "Hyperlink Text Tracking Protocol",
      "Home Text Transfer Program",
    ],
    correctIndex: 0,
    explanation: "HTTP is the protocol browsers use to request web pages.",
  },
  {
    id: "technology-003",
    category: "technology",
    prompt: "How is the decimal number 5 written in binary?",
    choices: ["100", "110", "111", "101"],
    correctIndex: 3,
    explanation: "101 in binary is 4 + 0 + 1.",
  },
  {
    id: "technology-004",
    category: "technology",
    prompt: "What does CPU stand for?",
    choices: [
      "Computer Power Unit",
      "Central Program Utility",
      "Central Processing Unit",
      "Core Peripheral Unit",
    ],
    correctIndex: 2,
    explanation: "The CPU carries out the instructions of a program.",
  },
  {
    id: "technology-005",
    category: "technology",
    prompt: "Which file extension usually indicates a compressed archive?",
    choices: [".zip", ".txt", ".png", ".html"],
    correctIndex: 0,
    explanation: "A .zip file bundles one or more files and compresses them.",
  },
  {
    id: "technology-006",
    category: "technology",
    prompt: "What does URL stand for?",
    choices: [
      "Universal Reference Link",
      "Unified Resource Locator",
      "Universal Routing Language",
      "Uniform Resource Locator",
    ],
    correctIndex: 3,
    explanation: "A URL is the address of a resource on the web.",
  },
  {
    id: "technology-007",
    category: "technology",
    prompt: "In hexadecimal, what decimal value does the digit F represent?",
    choices: ["10", "12", "15", "16"],
    correctIndex: 2,
    explanation: "Hexadecimal digits run 0 to 9 and then A to F, so F is 15.",
  },
  {
    id: "technology-008",
    category: "technology",
    prompt: "Which language is used to define the structure of a web page?",
    choices: ["CSS", "HTML", "SQL", "Python"],
    correctIndex: 1,
    explanation: "HTML marks up the content; CSS describes how it looks.",
  },
  {
    id: "technology-009",
    category: "technology",
    prompt: "What does RAM stand for?",
    choices: [
      "Read Access Memory",
      "Rapid Application Module",
      "Remote Access Memory",
      "Random Access Memory",
    ],
    correctIndex: 3,
    explanation: "RAM is the fast, temporary working memory of a computer.",
  },
  {
    id: "technology-010",
    category: "technology",
    prompt: "Which of these file extensions is used for images?",
    choices: [".mp3", ".jpg", ".docx", ".wav"],
    correctIndex: 1,
    explanation: "JPEG is a common compressed format for photographs.",
  },
  {
    id: "technology-011",
    category: "technology",
    prompt: "What does a compiler do?",
    choices: [
      "Translates source code into machine code",
      "Stores files on a disk",
      "Connects a computer to a network",
      "Draws images on the screen",
    ],
    correctIndex: 0,
    explanation: "A compiler turns human-readable code into instructions the CPU can run.",
  },
  {
    id: "technology-012",
    category: "technology",
    prompt: "Who is credited with inventing the World Wide Web in 1989?",
    choices: ["Bill Gates", "Steve Jobs", "Tim Berners-Lee", "Alan Turing"],
    correctIndex: 2,
    explanation: "Berners-Lee proposed the web while working at CERN.",
  },
  {
    id: "technology-013",
    category: "technology",
    prompt: "What is the decimal value of the binary number 1000?",
    choices: ["4", "6", "10", "8"],
    correctIndex: 3,
    explanation: "Each binary place is a power of two; 1000 is 2 to the power of 3.",
  },
  {
    id: "technology-014",
    category: "technology",
    prompt: "What does SQL stand for?",
    choices: [
      "Structured Query Language",
      "Simple Question Language",
      "Standard Quality Logic",
      "Sequential Query List",
    ],
    correctIndex: 0,
    explanation: "SQL is used to read and update relational databases.",
  },
  {
    id: "technology-015",
    category: "technology",
    prompt: "What is the general term for software designed to harm a computer?",
    choices: ["Firewall", "Malware", "Driver", "Compiler"],
    correctIndex: 1,
    explanation: "Malware is short for malicious software.",
  },
  {
    id: "technology-016",
    category: "technology",
    prompt: "In computing, what does GUI stand for?",
    choices: [
      "General User Input",
      "Global Unified Interface",
      "Graphical User Interface",
      "Guided User Instruction",
    ],
    correctIndex: 2,
    explanation: "A GUI lets people use windows, icons, and a pointer instead of typed commands.",
  },
  {
    id: "technology-017",
    category: "technology",
    prompt: "Which port number is the default for unencrypted HTTP traffic?",
    choices: ["21", "80", "443", "25"],
    correctIndex: 1,
    explanation: "Port 443 is the default for HTTPS, and 21 is FTP.",
  },
  {
    id: "technology-018",
    category: "technology",
    prompt: "What does Wi-Fi allow a device to do?",
    choices: [
      "Print documents",
      "Store data permanently",
      "Connect to a network without cables",
      "Charge its battery",
    ],
    correctIndex: 2,
  },
  {
    id: "technology-019",
    category: "technology",
    prompt: 'What does the "www" at the start of many web addresses stand for?',
    choices: ["World Wide Web", "World Web Window", "Wide World Web", "Web World Wide"],
    correctIndex: 0,
  },
  {
    id: "technology-020",
    category: "technology",
    prompt: "What is the name of the number system that uses only the digits 0 and 1?",
    choices: ["Decimal", "Octal", "Hexadecimal", "Binary"],
    correctIndex: 3,
    explanation: "Computers store and process data as binary digits, or bits.",
  },

  // ------------------------------------------------------------------- arts
  {
    id: "arts-001",
    category: "arts",
    prompt: "Who painted the Mona Lisa?",
    choices: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Botticelli"],
    correctIndex: 2,
    explanation: "Leonardo worked on the portrait in the early 1500s.",
  },
  {
    id: "arts-002",
    category: "arts",
    prompt: 'Which composer wrote the piano piece known as the "Moonlight Sonata"?',
    choices: ["Mozart", "Bach", "Chopin", "Beethoven"],
    correctIndex: 3,
    explanation: "Beethoven completed it in 1801; the nickname came later.",
  },
  {
    id: "arts-003",
    category: "arts",
    prompt: "How many strings does a standard violin have?",
    choices: ["4", "5", "6", "8"],
    correctIndex: 0,
    explanation: "The four strings are tuned G, D, A, and E.",
  },
  {
    id: "arts-004",
    category: "arts",
    prompt: "Claude Monet is most closely associated with which art movement?",
    choices: ["Cubism", "Impressionism", "Surrealism", "Baroque"],
    correctIndex: 1,
    explanation: "The movement took its name from Monet's painting Impression, Sunrise.",
  },
  {
    id: "arts-005",
    category: "arts",
    prompt: "Who painted the ceiling of the Sistine Chapel?",
    choices: ["Leonardo da Vinci", "Titian", "Caravaggio", "Michelangelo"],
    correctIndex: 3,
    explanation: "Michelangelo painted the ceiling between 1508 and 1512.",
  },
  {
    id: "arts-006",
    category: "arts",
    prompt: "Which instrument has 88 keys in its standard modern form?",
    choices: ["Piano", "Pipe organ", "Harpsichord", "Accordion"],
    correctIndex: 0,
    explanation: "A full-size piano has 52 white keys and 36 black keys.",
  },
  {
    id: "arts-007",
    category: "arts",
    prompt: "Vincent van Gogh was born in which country?",
    choices: ["Belgium", "Netherlands", "Germany", "France"],
    correctIndex: 1,
    explanation: "Van Gogh was Dutch, though he painted many of his famous works in France.",
  },
  {
    id: "arts-008",
    category: "arts",
    prompt: 'Which composer wrote the set of violin concertos called "The Four Seasons"?',
    choices: ["Handel", "Haydn", "Vivaldi", "Brahms"],
    correctIndex: 2,
    explanation: "Vivaldi published the concertos in 1725.",
  },
  {
    id: "arts-009",
    category: "arts",
    prompt: "In traditional painting, which three colours are called the primary colours?",
    choices: [
      "Red, yellow, and blue",
      "Red, green, and blue",
      "Cyan, magenta, and yellow",
      "Orange, green, and purple",
    ],
    correctIndex: 0,
    explanation: "Mixing pairs of these gives the secondary colours orange, green, and purple.",
  },
  {
    id: "arts-010",
    category: "arts",
    prompt: "Pablo Picasso helped found which art movement?",
    choices: ["Impressionism", "Dada", "Pop Art", "Cubism"],
    correctIndex: 3,
    explanation: "Picasso and Georges Braque developed Cubism in the early 1900s.",
  },
  {
    id: "arts-011",
    category: "arts",
    prompt: "The trumpet belongs to which family of instruments?",
    choices: ["Strings", "Woodwind", "Brass", "Percussion"],
    correctIndex: 2,
    explanation: "Brass instruments are played by buzzing the lips into a mouthpiece.",
  },
  {
    id: "arts-012",
    category: "arts",
    prompt: 'Who sculpted "The Thinker"?',
    choices: ["Michelangelo", "Auguste Rodin", "Donatello", "Bernini"],
    correctIndex: 1,
    explanation: "Rodin first modelled the figure in the 1880s.",
  },
  {
    id: "arts-013",
    category: "arts",
    prompt: 'Which composer wrote the opera "The Magic Flute"?',
    choices: ["Beethoven", "Mozart", "Schubert", "Wagner"],
    correctIndex: 1,
    explanation: "It premiered in Vienna in 1791, the year of Mozart's death.",
  },
  {
    id: "arts-014",
    category: "arts",
    prompt: "What is a painting that depicts a person's face and upper body called?",
    choices: ["Portrait", "Landscape", "Still life", "Mural"],
    correctIndex: 0,
  },
  {
    id: "arts-015",
    category: "arts",
    prompt: "A fresco is painted onto which surface?",
    choices: ["Stretched canvas", "Wood panel", "Glass", "Wet plaster"],
    correctIndex: 3,
    explanation: "The pigment bonds with the plaster as it dries.",
  },
  {
    id: "arts-016",
    category: "arts",
    prompt: 'Which artist painted "The Starry Night"?',
    choices: ["Monet", "Gauguin", "Van Gogh", "Cézanne"],
    correctIndex: 2,
    explanation: "Van Gogh painted it in 1889 while staying in southern France.",
  },
  {
    id: "arts-017",
    category: "arts",
    prompt: "How many performers make up a quartet?",
    choices: ["Two", "Three", "Five", "Four"],
    correctIndex: 3,
    explanation: "A string quartet has two violins, a viola, and a cello.",
  },
  {
    id: "arts-018",
    category: "arts",
    prompt: 'Which composer wrote the "Brandenburg Concertos"?',
    choices: ["Handel", "Bach", "Vivaldi", "Telemann"],
    correctIndex: 1,
    explanation: "Bach presented the six concertos to the Margrave of Brandenburg in 1721.",
  },
  {
    id: "arts-019",
    category: "arts",
    prompt: "What is a piece of music for a solo instrument accompanied by an orchestra called?",
    choices: ["Concerto", "Symphony", "Sonata", "Overture"],
    correctIndex: 0,
    explanation: "A symphony is for orchestra alone; a sonata is usually for one or two players.",
  },
  {
    id: "arts-020",
    category: "arts",
    prompt: "Salvador Dalí is best known for his work in which movement?",
    choices: ["Cubism", "Impressionism", "Surrealism", "Expressionism"],
    correctIndex: 2,
    explanation: "Surrealist artists drew on dreams and the unconscious.",
  },

  // ----------------------------------------------------------------- nature
  {
    id: "nature-001",
    category: "nature",
    prompt: "Which is the largest living land animal?",
    choices: ["Hippopotamus", "Giraffe", "White rhinoceros", "African elephant"],
    correctIndex: 3,
    explanation: "Adult male African elephants can weigh more than six tonnes.",
  },
  {
    id: "nature-002",
    category: "nature",
    prompt: "What do honeybees collect from flowers to turn into honey?",
    choices: ["Nectar", "Pollen", "Sap", "Dew"],
    correctIndex: 0,
    explanation: "Bees also gather pollen, but that is used as food for the colony.",
  },
  {
    id: "nature-003",
    category: "nature",
    prompt: "Which is the tallest living animal?",
    choices: ["Elephant", "Ostrich", "Giraffe", "Moose"],
    correctIndex: 2,
    explanation: "Giraffes can stand more than five metres tall.",
  },
  {
    id: "nature-004",
    category: "nature",
    prompt: "How many legs does a spider have?",
    choices: ["6", "8", "10", "12"],
    correctIndex: 1,
    explanation: "Insects have six legs; spiders and other arachnids have eight.",
  },
  {
    id: "nature-005",
    category: "nature",
    prompt: "What is a baby kangaroo called?",
    choices: ["Joey", "Cub", "Kit", "Calf"],
    correctIndex: 0,
    explanation: "A joey grows inside its mother's pouch after birth.",
  },
  {
    id: "nature-006",
    category: "nature",
    prompt: "Which is the only mammal capable of true, powered flight?",
    choices: ["Flying squirrel", "Sugar glider", "Bat", "Colugo"],
    correctIndex: 2,
    explanation: "The others can only glide between trees.",
  },
  {
    id: "nature-007",
    category: "nature",
    prompt: "Which gas do trees release into the air during photosynthesis?",
    choices: ["Nitrogen", "Carbon dioxide", "Methane", "Oxygen"],
    correctIndex: 3,
    explanation: "Plants take in carbon dioxide and give off oxygen.",
  },
  {
    id: "nature-008",
    category: "nature",
    prompt: "Which is the largest species of shark?",
    choices: ["Great white shark", "Whale shark", "Tiger shark", "Hammerhead shark"],
    correctIndex: 1,
    explanation: "Despite its size, the whale shark feeds mainly on plankton.",
  },
  {
    id: "nature-009",
    category: "nature",
    prompt: "What kind of animal is a Komodo dragon?",
    choices: ["Snake", "Amphibian", "Lizard", "Crocodilian"],
    correctIndex: 2,
    explanation: "It is the largest living lizard, native to a few Indonesian islands.",
  },
  {
    id: "nature-010",
    category: "nature",
    prompt: "Which biome has the heaviest rainfall and the greatest variety of species?",
    choices: ["Tropical rainforest", "Savanna", "Tundra", "Taiga"],
    correctIndex: 0,
    explanation: "Rainforests near the Equator stay warm and wet all year.",
  },
  {
    id: "nature-011",
    category: "nature",
    prompt: "How many hearts does an octopus have?",
    choices: ["One", "Three", "Two", "Four"],
    correctIndex: 1,
    explanation: "Two hearts pump blood to the gills and one to the rest of the body.",
  },
  {
    id: "nature-012",
    category: "nature",
    prompt: "What is the process by which a caterpillar becomes a butterfly called?",
    choices: ["Hibernation", "Migration", "Germination", "Metamorphosis"],
    correctIndex: 3,
    explanation: "The caterpillar transforms inside a chrysalis.",
  },
  {
    id: "nature-013",
    category: "nature",
    prompt: "Which is the largest animal known to have ever lived?",
    choices: ["Blue whale", "Argentinosaurus", "Sperm whale", "Megalodon"],
    correctIndex: 0,
    explanation: "Blue whales can reach around 30 metres and weigh well over 100 tonnes.",
  },
  {
    id: "nature-014",
    category: "nature",
    prompt: "Which part of a plant takes up water from the soil?",
    choices: ["Leaf", "Stem", "Flower", "Root"],
    correctIndex: 3,
    explanation: "Roots also anchor the plant and store food.",
  },
  {
    id: "nature-015",
    category: "nature",
    prompt: "Which of these animals is cold-blooded?",
    choices: ["Dolphin", "Crocodile", "Penguin", "Bat"],
    correctIndex: 1,
    explanation: "Reptiles rely on their surroundings to regulate body temperature.",
  },
  {
    id: "nature-016",
    category: "nature",
    prompt: "What is an animal that eats only plants called?",
    choices: ["Carnivore", "Omnivore", "Herbivore", "Insectivore"],
    correctIndex: 2,
    explanation: "Cows, deer, and rabbits are all herbivores.",
  },
  {
    id: "nature-017",
    category: "nature",
    prompt: "Which is the fastest land animal over a short sprint?",
    choices: ["Pronghorn", "Cheetah", "Greyhound", "Lion"],
    correctIndex: 1,
    explanation: "A cheetah can briefly exceed 100 km/h.",
  },
  {
    id: "nature-018",
    category: "nature",
    prompt: "Which of these animals is an amphibian?",
    choices: ["Turtle", "Gecko", "Salmon", "Frog"],
    correctIndex: 3,
    explanation: "Amphibians typically begin life in water and later breathe air.",
  },
  {
    id: "nature-019",
    category: "nature",
    prompt: "What is the cold northern forest biome of conifers such as spruce and fir called?",
    choices: ["Savanna", "Chaparral", "Taiga", "Steppe"],
    correctIndex: 2,
    explanation: "The taiga, or boreal forest, circles the globe south of the Arctic tundra.",
  },
  {
    id: "nature-020",
    category: "nature",
    prompt: "Which tree produces acorns?",
    choices: ["Oak", "Maple", "Birch", "Pine"],
    correctIndex: 0,
  },

  // ------------------------------------------------------------------- math
  {
    id: "math-001",
    category: "math",
    prompt: "What is 7 multiplied by 8?",
    choices: ["54", "56", "58", "64"],
    correctIndex: 1,
  },
  {
    id: "math-002",
    category: "math",
    prompt: "How many degrees are there in a right angle?",
    choices: ["45", "60", "90", "180"],
    correctIndex: 2,
    explanation: "Two right angles together make a straight line of 180°.",
  },
  {
    id: "math-003",
    category: "math",
    prompt: "What is the square root of 144?",
    choices: ["10", "11", "14", "12"],
    correctIndex: 3,
    explanation: "12 × 12 = 144.",
  },
  {
    id: "math-004",
    category: "math",
    prompt: "What is the value of pi rounded to two decimal places?",
    choices: ["3.14", "3.41", "3.12", "3.16"],
    correctIndex: 0,
    explanation: "Pi is the ratio of a circle's circumference to its diameter.",
  },
  {
    id: "math-005",
    category: "math",
    prompt: "How many sides does a hexagon have?",
    choices: ["5", "8", "6", "7"],
    correctIndex: 2,
    explanation: "The prefix hex- means six, as in honeycomb cells.",
  },
  {
    id: "math-006",
    category: "math",
    prompt: "What is 15% of 200?",
    choices: ["20", "30", "35", "25"],
    correctIndex: 1,
    explanation: "10% of 200 is 20 and 5% is 10, giving 30.",
  },
  {
    id: "math-007",
    category: "math",
    prompt: "Which of these numbers is prime?",
    choices: ["13", "15", "21", "27"],
    correctIndex: 0,
    explanation: "A prime has exactly two factors: 1 and itself.",
  },
  {
    id: "math-008",
    category: "math",
    prompt: "What do the interior angles of any triangle add up to?",
    choices: ["90°", "360°", "270°", "180°"],
    correctIndex: 3,
    explanation: "The angles of a quadrilateral add up to 360°.",
  },
  {
    id: "math-009",
    category: "math",
    prompt: "What is 2 raised to the power of 5?",
    choices: ["16", "32", "64", "25"],
    correctIndex: 1,
    explanation: "2 × 2 × 2 × 2 × 2 = 32.",
  },
  {
    id: "math-010",
    category: "math",
    prompt: "What is the next number in the sequence 2, 4, 8, 16?",
    choices: ["24", "20", "32", "18"],
    correctIndex: 2,
    explanation: "Each term is double the one before it.",
  },
  {
    id: "math-011",
    category: "math",
    prompt: "What is the perimeter of a square whose sides are each 5 cm long?",
    choices: ["20 cm", "25 cm", "10 cm", "15 cm"],
    correctIndex: 0,
    explanation: "Perimeter is the total length of all four sides: 4 × 5 cm.",
  },
  {
    id: "math-012",
    category: "math",
    prompt: "How many zeros are there in one million written as a number?",
    choices: ["4", "5", "7", "6"],
    correctIndex: 3,
    explanation: "One million is written as 1,000,000.",
  },
  {
    id: "math-013",
    category: "math",
    prompt: "What is 100 divided by 4?",
    choices: ["20", "30", "25", "40"],
    correctIndex: 2,
  },
  {
    id: "math-014",
    category: "math",
    prompt: "What is a triangle with three equal sides called?",
    choices: ["Equilateral", "Isosceles", "Scalene", "Right-angled"],
    correctIndex: 0,
    explanation: "An isosceles triangle has two equal sides; a scalene has none.",
  },
  {
    id: "math-015",
    category: "math",
    prompt: "What is the area of a rectangle that is 6 units long and 4 units wide?",
    choices: ["10", "20", "12", "24"],
    correctIndex: 3,
    explanation: "Area of a rectangle is length × width.",
  },
  {
    id: "math-016",
    category: "math",
    prompt: "Which is the only even prime number?",
    choices: ["4", "2", "0", "6"],
    correctIndex: 1,
    explanation: "Every other even number is divisible by 2, so it cannot be prime.",
  },
  {
    id: "math-017",
    category: "math",
    prompt: "How many minutes are there in three hours?",
    choices: ["120", "150", "90", "180"],
    correctIndex: 3,
    explanation: "3 × 60 = 180.",
  },
  {
    id: "math-018",
    category: "math",
    prompt: "What is 9 squared?",
    choices: ["81", "72", "91", "18"],
    correctIndex: 0,
    explanation: "Squaring a number means multiplying it by itself.",
  },
  {
    id: "math-019",
    category: "math",
    prompt: "Which Roman numeral represents 50?",
    choices: ["C", "L", "D", "X"],
    correctIndex: 1,
    explanation: "X is 10, C is 100, and D is 500.",
  },
  {
    id: "math-020",
    category: "math",
    prompt: "What is one quarter written as a decimal?",
    choices: ["0.4", "0.14", "0.25", "0.75"],
    correctIndex: 2,
    explanation: "1 ÷ 4 = 0.25.",
  },
];

/** Bundled, offline question bank for the Daily quiz widget. All wording is original. */
export const BUILTIN_DAILY_QUIZ_PACK: IDailyQuizPack = {
  id: "builtin-general-v1",
  name: "General knowledge",
  version: "1.0.0",
  questions: QUESTIONS,
};
