/**
 * Embeds `doc/CHANGELOG.md` into the extension settings UI.
 * Run from repo root: `pnpm generate:settings-changelog`
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..", "..");
const CHANGELOG_PATH = join(REPO_ROOT, "doc", "CHANGELOG.md");
const PACKAGE_JSON_PATH = join(__dirname, "..", "package.json");
const OUT_FILE = join(__dirname, "..", "lib", "changelog", "changelog.generated.ts");

const markdown = await readFile(CHANGELOG_PATH, "utf8");
const packageJson = JSON.parse(await readFile(PACKAGE_JSON_PATH, "utf8")) as { version?: string };
const extensionVersion =
  typeof packageJson.version === "string" && packageJson.version.trim().length > 0
    ? packageJson.version.trim()
    : "0.0.0";

const header = `/**
 * AUTO-GENERATED by \`apps/extension/scripts/generate-settings-changelog.ts\`.
 * Source: doc/CHANGELOG.md (repo root)
 * Do not edit by hand — run \`pnpm generate:settings-changelog\` after doc/CHANGELOG.md changes or version bumps.
 */
`;

const body = `export const SETTINGS_CHANGELOG_EXTENSION_VERSION = ${JSON.stringify(extensionVersion)};\n\nexport const SETTINGS_CHANGELOG_MARKDOWN = ${JSON.stringify(markdown)};\n`;

await writeFile(OUT_FILE, `${header}${body}`, "utf8");
console.log(
  `Wrote settings changelog (${markdown.length} chars) for v${extensionVersion} → ${OUT_FILE}`,
);
