/**
 * Fetches https://www.unsuck-it.com/classics and regenerates the built-in humor lines
 * for Classic jargon. Run from repo root:
 *   pnpm scrape:unsuck-classics
 *
 * Source content is authored by Unsuck It; ensure redistribution complies with their terms.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DENY_SUBSTRINGS = ["child porn", "cp ", "rape", "kill yourself", "kys", "nazi", "hitler"];

function passesBuiltinHardFilter(line: string): boolean {
  const lower = line.toLowerCase();
  return !DENY_SUBSTRINGS.some((s) => lower.includes(s));
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = join(__dirname, "..", "lib", "humor", "unsuck-classics-lines.generated.ts");
const SOURCE_URL = "https://www.unsuck-it.com/classics";

function decodeHtmlEntities(s: string): string {
  return s
    .replace(/&nbsp;/gi, " ")
    .replace(/&ndash;/gi, "\u2013")
    .replace(/&mdash;/gi, "\u2014")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/&#(\d+);/g, (_: string, d: string) => String.fromCodePoint(Number(d)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_: string, h: string) =>
      String.fromCodePoint(parseInt(h, 16)),
    );
}

function stripHtml(s: string): string {
  return decodeHtmlEntities(s.replace(/<br\s*\/?>/gi, " ").replace(/<[^>]+>/g, " "));
}

function normalizeDefinitionText(s: string): string {
  return (
    s
      // Accordion widget artifacts (e.g. "Item de" prefix from Squarespace list markup)
      .replace(/^Item\s+de\s*/i, "")
      .replace(/\s+([.,;:!?])/g, "$1")
      .replace(/\s+,/g, ",")
      .replace(/\s+\)/g, ")")
      .replace(/\(\s+/g, "(")
      .replace(/\s+/g, " ")
      .trim()
  );
}

function capitalizeTerm(term: string): string {
  const t = term.trim();
  if (t.length <= 6 && /^[A-Z0-9.]+$/.test(t)) return t;
  return t.charAt(0).toUpperCase() + t.slice(1);
}

interface IScrapedEntry {
  term: string;
  text: string;
}

function parseEntries(html: string): IScrapedEntry[] {
  const out: IScrapedEntry[] = [];
  const liRe = /<li class="accordion-item">([\s\S]*?)<\/li>/g;
  let m;
  while ((m = liRe.exec(html))) {
    const block = m[1];
    const titleM = block.match(/class="accordion-item__title"[^>]*>\s*([^<]+?)\s*</);
    if (!titleM) continue;
    const term = titleM[1].trim();
    const descM = block.match(/accordion-item__description[\s\S]*?>([\s\S]*?)<\/div>/);
    if (!descM) continue;
    const text = normalizeDefinitionText(stripHtml(descM[1]));
    if (!text) continue;
    out.push({ term, text });
  }
  return out;
}

function toLine(term: string, def: string): string {
  return `${capitalizeTerm(term)} — ${def}`;
}

const html = await fetch(SOURCE_URL).then((r) => {
  if (!r.ok) throw new Error(`Fetch failed ${r.status}`);
  return r.text();
});

const entries = parseEntries(html);
if (entries.length < 10) {
  throw new Error(
    `Expected many glossary entries; got ${entries.length}. Page structure may have changed.`,
  );
}

const lines = entries.map((e) => toLine(e.term, e.text));

for (const line of lines) {
  if (!passesBuiltinHardFilter(line)) {
    throw new Error(
      `Line blocked by built-in safety filter; edit upstream or the scraper: ${line.slice(0, 120)}…`,
    );
  }
}

const header = `/**
 * AUTO-GENERATED by \`apps/extension/scripts/scrape-unsuck-classics.ts\`.
 * Source: ${SOURCE_URL}
 * Do not edit by hand — re-run the scraper after upstream HTML changes.
 */
`;

const body = `export const UNSUCK_CLASSICS_SCRAPED_LINES: readonly string[] = [\n${lines
  .map((line) => `  ${JSON.stringify(line)},\n`)
  .join("")}];\n`;

await mkdir(dirname(OUT_FILE), { recursive: true });
await writeFile(OUT_FILE, `${header}${body}`, "utf8");
console.log(`Wrote ${lines.length} lines to ${OUT_FILE}`);
