/**
 * Fetches https://www.unsuck-it.com/classics and regenerates the built-in humor lines
 * for Classic jargon. Run from repo root:
 *   pnpm scrape:unsuck-classics
 *
 * Source content is authored by Unsuck It; ensure redistribution complies with their terms.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  parseUnsuckClassicsHtml,
  UNSUCK_CLASSICS_SOURCE_URL,
} from "../lib/humor/unsuck-classics-parse";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = join(__dirname, "..", "lib", "humor", "unsuck-classics-lines.generated.ts");

const html = await fetch(UNSUCK_CLASSICS_SOURCE_URL).then((r) => {
  if (!r.ok) throw new Error(`Fetch failed ${r.status}`);
  return r.text();
});

const lines = parseUnsuckClassicsHtml(html);

const header = `/**
 * AUTO-GENERATED by \`apps/extension/scripts/scrape-unsuck-classics.ts\`.
 * Source: ${UNSUCK_CLASSICS_SOURCE_URL}
 * Do not edit by hand — re-run the scraper after upstream HTML changes.
 */
`;

const body = `export const UNSUCK_CLASSICS_SCRAPED_LINES: readonly string[] = [\n${lines
  .map((line) => `  ${JSON.stringify(line)},\n`)
  .join("")}];\n`;

await mkdir(dirname(OUT_FILE), { recursive: true });
await writeFile(OUT_FILE, `${header}${body}`, "utf8");
console.log(`Wrote ${lines.length} lines to ${OUT_FILE}`);
