import type { THumorIntensity } from "../settings";

/** Built-in pack used when Settings → Chaos → Gen-Z voice is selected. */
export const GEN_Z_PACK_ID = "gen_z" as const;

/** Built-in pack for the “classic jargon” satirical glossary voice. */
export const UNSUCK_CLASSICS_PACK_ID = "unsuck_classics" as const;

export interface IBuiltinPack {
  id: string;
  name: string;
  maxIntensity: THumorIntensity;
  lines: string[];
}

export const BUILTIN_PACKS: IBuiltinPack[] = [
  {
    id: "office_absurd",
    name: "Office absurd",
    maxIntensity: "mild",
    lines: [
      "Sync-up about the sync-up: courage.",
      "Your calendar is a museum of good intentions.",
      "Another tab? Bold. Another meeting? Bolder.",
      "Another tab? Bold. Another window? Bolder.",
      "Inbox zero? Bold. Inbox archeology? Bolder.",
      "A \u201Cquick question\u201D? Bold. A \u201Cquick sync\u201D? Bolder.",
      "Snooze the alarm? Bold. Snooze accountability? Bolder.",
      "One more scroll? Bold. One more status report? Bolder.",
      "Read the docs? Bold. Read the room? Bolder.",
      "Ship on Friday? Bold. \u201CWe\u2019ll hotfix weekend\u201D? Bolder.",
      "Reply today? Bold. Reply-all with thoughts? Bolder.",
      "Stand-up honest? Bold. Stand-up performance art? Bolder.",
      "Debug with prints? Bold. Debug with vibes? Bolder.",
      "Refactor later? Bold. Refactor in your heart? Bolder.",
      "Add a shortcut? Bold. Add a dependency? Bolder.",
      "Dark mode? Bold. Dark night of the soul for legacy code? Bolder.",
      "Slack react? Bold. Slack manifesto? Bolder.",
      "Bookmark this? Bold. Bookmark tab 200? Bolder.",
      "Close some tabs? Bold. Close the laptop? Bolder.",
      "Work from home? Bold. Work from bed? Bolder.",
      "Camera on? Bold. Virtual background a crime scene? Bolder.",
      "Unmute to speak? Bold. Unmute to eat chips? Bolder.",
      "Shared screen? Bold. Shared screen with 40 tabs? Bolder.",
      "Pomodoro 25? Bold. Pomodoro \u201Cjust one more\u201D? Bolder.",
      "Calendar blocked? Bold. Calendar theater? Bolder.",
      "Mute notifications? Bold. Mute your conscience? Bolder.",
      "Async updates? Bold. Async avoidance? Bolder.",
      "LGTM in chat? Bold. LGTM on prod without tests? Bolder.",
      "Rubber duck debug? Bold. Rubber duck middle manager? Bolder.",
      "Git blame someone else? Bold. Git blame past you? Bolder.",
      "New keyboard shortcut? Bold. New Chrome extension? Bolder.",
      "Reply-all is not a personality trait.",
      "Coffee first. Questions never.",
      "The agenda is: survive the agenda.",
      "Your productivity hacks have productivity hacks.",
      "You emailed yourself a reminder. That\u2019s a genre now.",
      "Meeting declined. Self-respect accepted.",
      "That recurring meeting is just ambient dread on a schedule.",
      "Your desk plant has seen things. Terrible, tabbed things.",
      "You put \u2018EOD\u2019 in the message. You both know it\u2019s a lie.",
      "Action items from a meeting about action items. Circle of corporate life.",
      "Your workflow has more tabs than your browser does.",
      "Out-of-office reply energy, but you\u2019re at your desk.",
      "The standup was 40 minutes. No one stood up.",
      "You restarted your browser and called it a mental-health day.",
      "Eating lunch at your desk isn\u2019t multitasking; it\u2019s survival.",
      "Your browser history is more honest than your time sheet.",
      "The WiFi went down and you briefly knew peace.",
    ],
  },
  {
    id: "dev_snark",
    name: "Dev snark",
    maxIntensity: "spicy",
    lines: [
      "It works on my machine\u2122 \u2014 now a UNESCO site.",
      "semver is just vibes with extra steps.",
      "Your rubber duck filed for emotional damages.",
      "I\u2019ll fix it in post\u2026 said the backend, lying.",
      "Merge conflict: you vs past you. Past you was worse.",
      "Your git log reads like a slow descent into madness.",
      "That TODO comment has been there since the repo was born. It\u2019s load-bearing now.",
      "You wrote \u2018temporary fix\u2019 in 2019. It\u2019s permanent and scared.",
      "Your code review comment is three paragraphs. The diff is one line.",
      "npm install: the package manager has 847 opinions and none of them agree.",
      "console.log(\u2018here\u2019) \u2014 the industry\u2019s most deployed debugging strategy.",
      "\u2018Just a small refactor,\u2019 said the dev, mass-renaming 200 files.",
      "Your branch name is longer than your attention span.",
      "The codebase has layers. Like an onion. It also makes you cry.",
      "You mass-deleted node_modules and felt something close to joy.",
      "The README says \u2018easy setup.\u2019 The README is a liar.",
      "You named the variable \u2018temp2.\u2019 There is no temp1. There never was.",
      "Your staging environment is production with a fake mustache.",
      "Stack Overflow: copy, paste, pray, ship.",
      "\u2018We\u2019ll document it later\u2019 is the developer\u2019s \u2018see you never.\u2019",
      "Your regex works. Nobody knows why. Especially you.",
      "You cargo-culted that config from a 2017 blog post and it still holds.",
      "CI is green. The bar is underground and you cleared it.",
      "Your PR title is \u2018misc fixes.\u2019 Your PR is 73 files.",
      "The deploy script has a comment that just says \u2018sorry.\u2019",
    ],
  },
  {
    id: "demotivation",
    name: "Demotivation",
    maxIntensity: "spicy",
    lines: [
      "Shoot for the moon. Miss. Orbit debris forever.",
      "Teamwork makes the dream work \u2014 the dream is nap time.",
      "You miss 100% of the naps you don\u2019t take.",
      "Rise and grind? More like rise and find tab 47.",
      "Believe in yourself \u2014 statistically risky, but brave.",
      "Hang in there \u2014 the ceiling is already giving up.",
      "Today is a gift. That\u2019s why it\u2019s called \u2018the present.\u2019 No returns.",
      "The journey of a thousand miles begins with closing zero tabs.",
      "Dream big. Achieve medium. Settle for whatever loads first.",
      "You\u2019re one tab away from greatness. You\u2019ve been one tab away for hours.",
      "Good things come to those who wait. You\u2019ve been waiting. Any day now.",
      "Think outside the box. The box has 90 tabs in it.",
      "Every day is a fresh start. Every start is a new tab.",
      "The only limit is yourself. And your RAM. Mostly your RAM.",
      "Be the change you wish to see in the world. The world is your tab bar.",
      "Winners never quit. They just open a new tab and forget why.",
      "Success is a staircase, not an elevator. You took the escalator to lunch.",
      "You didn\u2019t come this far to only come this far. But here you are.",
      "Failure is not the opposite of success. It\u2019s your current tab count.",
      "Make today count. Your browser is already counting tabs for you.",
      "Keep pushing forward. Your RAM is pushing back.",
      "Great things never came from closing tabs. Wait\u2026 actually they do.",
      "Seize the day. Or at least seize a bookmark.",
      "You are capable of amazing things. Tab management is not one of them.",
      "Stars can\u2019t shine without darkness. Your screen is at 100% brightness though.",
    ],
  },
  {
    id: "tab_shame",
    name: "Tab shame",
    maxIntensity: "mild",
    lines: [
      "New tab energy: chaotic neutral.",
      "You opened a new tab like you pay rent here.",
      "Procrastination speedrun: any% WR pace.",
      "Bookmark it? Never heard of her.",
      "Focus is a spectrum. You\u2019re exploring the whole rainbow.",
      "Your tab bar is doing the most, and it\u2019s not the serve you think.",
      "Somewhere, a browser engineer just felt a disturbance.",
      "You don\u2019t have tabs. You have a digital hoarding problem.",
      "Close a tab? In this economy?",
      "Your tab bar just filed a noise complaint.",
      "Each tab is a promise you made to yourself. You\u2019re a serial promise-breaker.",
      "You didn\u2019t need that tab. But you opened it. Because you\u2019re free.",
      "Tab count: classified. Dignity: negotiable.",
      "That tab from last Tuesday is still waiting. It believes in you.",
      "Your browser has more open tabs than you have open conversations.",
      "You scrolled past your target tab three times. It\u2019s camouflaged now.",
      "Some people collect stamps. You collect tabs. Neither is useful.",
      "Your tab bar looks like a barcode.",
      "You have tabs older than some of your friendships.",
      "Ctrl+T is your love language.",
      "One does not simply close a tab. One opens three more.",
      "Your browser suggested you take a break. You opened a tab about it.",
      "Tab bankruptcy: when you close all of them and start fresh. You\u2019ll never do it.",
      "That tab has been open so long, the page redesigned itself.",
      "You and your 60 tabs: a love story no one asked for.",
    ],
  },
  {
    id: "error_messages",
    name: "Error messages",
    maxIntensity: "mild",
    lines: [
      "404: Motivation not found.",
      "Success: undefined",
      "Stack overflow: tabs > RAM > dignity",
      "NullPointerException: attention span",
      "HTTP 418: I\u2019m a teapot. You\u2019re a tab hoarder.",
      "ERR_CONNECTION_REFUSED: productivity server is down.",
      "FATAL: too many tabs open. Please close your eyes instead.",
      "WARNING: your last save point was three hours ago.",
      "SEGFAULT: ambition exceeded available focus.",
      "TIMEOUT: waiting for you to close a tab since startup.",
      "ERR_INSUFFICIENT_WILLPOWER: cannot complete task.",
      "DEPRECATED: your plan to \u2018just check one thing.\u2019",
      "PANIC: kernel of self-doubt detected.",
      "ENOSPC: no space left on tab bar.",
      "ERR_TOO_MANY_REDIRECTS: you keep going back to that one site.",
      "WARN: unhandled promise to be productive today.",
      "TypeError: \u2018five minutes\u2019 is not assignable to type \u2018number\u2019 (actual: 45 minutes).",
      "503: Motivation temporarily unavailable. Try again after coffee.",
      "SIGTERM: your focus process was killed by tab 34.",
      "ERR_CERT_DATE_INVALID: your to-do list expired six weeks ago.",
      "OUT_OF_MEMORY: too many thoughts, not enough RAM.",
      "PERMISSION_DENIED: you are not authorized to procrastinate. (Proceeding anyway.)",
      "DEADLOCK: can\u2019t close tabs until you read them. Can\u2019t read them until you close tabs.",
      "HEAP_OVERFLOW: ambitions allocated but never freed.",
      "EXIT_CODE 1: left the house without closing your tabs.",
    ],
  },
  {
    id: "spicy_safe",
    name: "Spicy (reviewed)",
    maxIntensity: "spicy",
    lines: [
      "This tab count is not a flex. It\u2019s a cry for help.",
      "Ship it? Buddy, you can\u2019t even ship yourself to bed on time.",
      "Touch grass? You can\u2019t even touch \u2018Save\u2019.",
      "Your backlog has a backlog. Inception, but stupid.",
      "Zero inbox is a myth. Like \u2018just one more tab.\u2019",
      "Your browser history should require a support group.",
      "You call it \u2018research.\u2019 Your therapist calls it \u2018avoidance.\u2019",
      "The weather widget knows you haven\u2019t been outside.",
      "You set a reminder to set a reminder. Peak performance.",
      "Your attention span and your WiFi have the same reliability.",
      "You treat \u2018close all tabs\u2019 like it\u2019s an act of emotional violence.",
      "Productivity hack: stare at the screen harder. It\u2019s not working? Stare harder.",
      "You opened Settings to change something. You forgot what. Classic.",
      "You bookmarked an article about focus. You haven\u2019t read it.",
      "Dark mode isn\u2019t a personality. Your tab count is, though.",
      "Your new tab page sees you more than your friends do.",
      "You googled \u2018how to be more productive\u2019 and opened four more tabs.",
      "That motivational quote isn\u2019t helping. Neither is tab 58.",
      "You\u2019ve customized your new tab page more than your actual life.",
      "Your search history is just the same three questions, rephrased.",
      "Somewhere a minimalist just felt a great disturbance in the tabs.",
      "You clicked \u2018remind me later.\u2019 It\u2019s later. You clicked it again.",
      "The clock on your screen knows you\u2019ve been here too long.",
      "Your to-do list is just a guilt-powered spreadsheet.",
      "Closing tabs feels like deleting memories. Bad ones, but still.",
    ],
  },
  {
    id: "existential",
    name: "Existential browsing",
    maxIntensity: "mild",
    lines: [
      "You opened a new tab. The void opened a new tab back.",
      "What if tabs are just thoughts you refuse to finish?",
      "Every closed tab is a road not taken. You have taken none of them.",
      "The scroll is infinite. Your time is not.",
      "You stare at the screen. The screen stares back. Neither blinks.",
      "A new tab is just optimism with a loading spinner.",
      "Somewhere between tab 1 and tab 40, you lost the plot.",
      "Are you browsing the internet, or is the internet browsing you?",
      "Your new tab page is the only place that truly knows you.",
      "You\u2019ll close the tabs tomorrow. Tomorrow, you\u2019ll say it again.",
      "If a tab is open and no one reads it, does it consume RAM? Yes.",
      "Each tab is a parallel universe where you were going to do something.",
      "The cursor blinks. You blink. Nothing else happens.",
      "You searched for meaning. You found a listicle.",
      "The browser remembers everything. You remember nothing.",
      "Time is a flat circle. Your tab bar is a flat line.",
      "You came here for a reason. The reason has been lost to history.",
      "Somewhere in these tabs is the answer. You\u2019ve forgotten the question.",
      "Opening a new tab: the eternal return of the unfinished task.",
      "Philosophy is just googling \u2018why\u2019 with more steps.",
    ],
  },
  {
    id: "passive_aggressive",
    name: "Passive-aggressive coach",
    maxIntensity: "spicy",
    lines: [
      "Oh, another new tab? Sure. You\u2019re the boss. Clearly.",
      "No no, take your time. The tabs will wait. They always do.",
      "You could close a tab. Just a thought. No pressure. Really.",
      "I\u2019m not saying your tab count is a problem. I\u2019m implying it.",
      "Oh, you changed the wallpaper again? That\u2019ll fix everything.",
      "Per my last banner, maybe close a tab?",
      "Just circling back on that tab you said you\u2019d read. Third time.",
      "Great job opening that tab. Truly groundbreaking work.",
      "Sure, add another extension. That\u2019s definitely what\u2019s missing.",
      "I see you customized the clock. Time management solved.",
      "You checked the weather. Bold move for someone who won\u2019t go outside.",
      "Going forward, let\u2019s align on maybe doing literally anything.",
      "As previously mentioned, those tabs aren\u2019t reading themselves.",
      "Just to clarify, you know bookmarks exist, right?",
      "Hope this banner finds you well. And productive. Which I doubt.",
      "Happy to help! Just kidding. Close your own tabs.",
      "Friendly reminder: you opened that tab 3 hours ago. Friendly.",
      "Not to be that banner, but your tab bar is giving red flags.",
      "Looping in your conscience on this tab situation.",
      "Please advise on when you plan to actually close something.",
    ],
  },
  {
    id: UNSUCK_CLASSICS_PACK_ID,
    name: "Classic jargon",
    maxIntensity: "mild",
    lines: [
      "Synergy — when two wrong ideas hold hands and call it strategy.",
      "Circle back — meet again so nobody has to decide today.",
      "Deep dive — read the subject line out loud and call it research.",
      "Bandwidth — polite way to say “no” while sounding generous.",
      "Touch base — schedule a meeting to discuss scheduling meetings.",
      "Best-in-class — the least embarrassing option from a biased slide deck.",
      "Leverage — use a noun you do not understand until the sentence sounds serious.",
      "Quick win — look busy before anyone checks the spreadsheet.",
      "Low-hanging fruit — tasks we mention loudly so we can ignore the hard ones.",
      "Action items — regrets written down in bullet form.",
      "Stakeholder — anyone CC\u2019d enough times to deserve blame.",
      "Alignment — agreeing the chart is pretty while avoiding the question.",
      "Thought leadership — tweeting a platitude and booking a keynote.",
      "North star metric — the number we worship until quarterly panic.",
      "Scaling — doing the same chaos with more headcount.",
      "Optimize — rearrange labels until morale improves.",
      "Stakeholder sync — empathy theater with a calendar invite.",
      "Mission-critical — important enough to interrupt lunch, not enough to fund.",
      "Culture fit — “we like people who already agree with us.”",
      "Run it up the flagpole — test if blame can fly before we commit.",
      "Rightsize — resize, but with fewer apologies.",
      "Operationalize — turn a memo into a process that owns you.",
      "Paradigm shift — rename the folder and declare victory.",
      "Hypergrowth — velocity measured in anxiety, not revenue.",
      "Customer-centric — we thought about users during the deck animation.",
      "Swim lane — your box in the RACI where responsibility evaporates.",
      "New tab — a fresh canvas for the same procrastination.",
      "Bookmark bar — a graveyard of intentions with favicon headstones.",
      "Async update — typing “following up” into the void.",
      "Multitasking — believing tab 40 is still one coherent errand.",
    ],
  },
  {
    id: GEN_Z_PACK_ID,
    name: "Gen Z",
    maxIntensity: "mild",
    lines: [
      "Another tab? That\u2019s giving main-character energy. No cap.",
      "24-hour clock? Bestie, you can\u2019t even manage 24 tabs.",
      "Bookmark who? Bestie, you\u2019re not even bookmarking focus.",
      "The way you\u2019re hoarding tabs is\u2026 a choice. Respectfully.",
      "Touch grass? You\u2019re choosing Chrome tabs. Vibe check: failed.",
      "This ain\u2019t it \u2014 it\u2019s giving procrastination lore.",
      "You\u2019re not built different; you\u2019re built like tab 87.",
      "Rent free in your browser and still no clarity? Wild.",
      "Slay? More like slay your RAM. Those tabs are not it.",
      "Lowkey you\u2019re speedrunning burnout with extra tabs.",
      "NPC arc: open tab, pretend you\u2019ll read it, repeat.",
      "It\u2019s giving \u2018I\u2019ll read this later\u2019 since forever.",
      "You\u2019re cooking\u2026 absolutely nothing. Mid workflow energy.",
      "Fr fr your backlog is the real final boss.",
      "Skill issue (tabs edition).",
      "She\u2019s not girlbossing; she\u2019s tab-hoarding in HD.",
      "Main character syndrome, supporting cast tab count.",
      "That tab pile is sending me \u2014 and not in a good way.",
      "Delulu is the solulu, except for this tab count: still real.",
      "Clock app who? You live here now. Stay hydrated.",
      "This tab bar is my villain origin story.",
      "Tabs on tabs on tabs. It\u2019s giving anxiety-core.",
      "Respectfully, your browser is cooked.",
      "You\u2019re gatekeeping productivity from yourself.",
      "Your browser tabs are a whole cinematic universe at this point.",
      "The Roman Empire of tab counts. You think about it daily.",
      "That\u2019s a lot of tabs, and I\u2019m here for the chaos. Actually no.",
      "You\u2019re so real for this mess. Not in a good way.",
      "POV: you told yourself \u2018just one more tab\u2019 40 tabs ago.",
      "Not the tab hoarding on main. We see you.",
      "Ick: someone who says they\u2019ll close tabs later and never does. It\u2019s you.",
      "Live, laugh, 47 unread tabs.",
      "Your browser tabs just dropped a diss track about you.",
      "No thoughts, just tabs. Literally zero thoughts.",
      "Tell me you have commitment issues without telling me. Oh wait, your tab bar.",
      "Understood the assignment? You can\u2019t even find the assignment tab.",
      "Era check: you\u2019re in your \u2018too many tabs\u2019 era. It\u2019s been 3 years.",
      "The way this tab bar is giving chaos goblin energy\u2026",
      "Ate and left no crumbs? You ate nothing and left 50 tabs.",
      "You really said \u2018I\u2019ll organize later\u2019 and chose unhinged.",
    ],
  },
];
